### ISSUE TITLE
package.json repository url

### ISSUE THREAD

**Issue by fanatid** [bitcoinjs/bs58check#1]
Please fix URLs in package.json
OOI: why this repo in bitcoinjs org? not in cryptocoinjs?

**Comment by dcousens** [comment]
Fixed in 511fca2bedeef9ca82eda8b1fcdf2bcd17093700

**Comment by dcousens** [comment]
@fanatid its a good question.  I don't have a valid answer for you other than I moved it here at some point. 
The distinction between cryptocoinjs and bitcoinjs as organizations is lacking,  and I'm not sure what the right answer should be.

**Comment by jprichardson** [comment]
>  I don't have a valid answer for you other than I moved it here at some point.

Given that base 58 check encoding is applicable to pretty much every crypto currency, I support a move to `cryptocoinjs`. Also, it's not like there'd be any admin concerns as you're (@dcousens) an owner too.

Overall though, it's ultimately your call @dcousens.

**Comment by dcousens** [comment]
@jprichardson this is true,  but where do we draw the line?  Ultimately should `BIP32` be moved too?  `wif`?
`BIP39`?

All these are tools in common usage across multiple cryptos,  and yet,  they have a clear origin in bitcoin.
I also like the idea of keeping some of the "primitive" basics as close together as possible for easy exploration by users.

**Comment by fanatid** [comment]
Should bitcoinjs.org work? // Can't open
The revolutionary thing is moving all bitcoinjs packages to cryptocoinjs.
Or keep all as is, as main rule: if thing is working — don't touch :)

**Comment by jprichardson** [comment]
I'd say, `wif` yes. BIPS, no. The intent and purpose of BIPS is clearly targeted towards Bitcoin and our implementations should reflect that, despite being usable for other coins. Also, the naming of 'BIPS' seems consistent with the `bitcoinjs` org.

Actually, it seems to me that crypto coin primitives/code should be in `cryptocoinjs` and bitcoin specific code should be in `bitcoinjs`. Part of the advantages here would be discoverability IMHO.

We're not at a point yet where it matters too much, but I think we will eventually. I'll be working on the new BIP32 module (w/ elliptic) within the next couple of months and I eventually want to work on BIP47 (payment codes). Over time, bitcoinjs may get cluttered. 

Regardless, I don't care enough to push for these changes at the moment, but those are my thoughts.

**Comment by dcousens** [comment]
@jprichardson agreed with you on all points.  Agreed,  not ready to push for this kind of re-organization right now,  but I agree we should probably re-consolidate after the `BIP32` module is properly extracted.

**Comment by jprichardson** [comment]
>  I'm also not ready to push for this kind of re-organization right now, 

Totally cool. We can revisit when it may be more of a problem.
