### ISSUE TITLE
Custom checksum function?

### ISSUE THREAD

**Issue by fanatid** [bitcoinjs/bs58check#10]
Thoughts about custom checksum function as optional argument?
for example Decred uses double blake256 instead double sha256

cc @dcousens @jprichardson

**Comment by jprichardson** [comment]
I'd love to see this 😄 

We could pass a second parameter for the checksum function and by default it's `sha256x2`. No breaking API change, so it could be a minor bump.

Thoughts @dcousens?

**Comment by dcousens** [comment]
My question is simply... is it `bs58check` then? Or just base58 with a custom checksum?

**Comment by fanatid** [comment]
hmmm, do you mean create another project which will create `bs58check` with `sha256x2`? like `base-x` and `bs58`?

bs58check in Decred: https://github.com/decred/bitcore/blob/master-new/lib/encoding/base58check.js

**Comment by dcousens** [comment]
I'm saying,  the definition of `bs58check` is base58 with a SHA256x2 checksum.
I don't think any derivation of `bs58check` should exist where the checksum could be different.

**Comment by fanatid** [comment]
but as you see other people (Decred) uses another checksum function in `bs58check`
my proposal now is create two repositories like `base-x` and `bs58`

**Comment by jprichardson** [comment]
> I'm saying, the definition of bs58check is base58 with a SHA256x2 checksum.

Since the proposed modification is a second optional parameter, the API would not break compatibility, is there much for us to be concerned about?

**Comment by dcousens** [comment]
@fanatid how about something like `base-x-check`?

**Comment by fanatid** [comment]
`base-x-check(codec, checksumFn)` is good for me, i.e. for `bs58check`: `base-x-check(bs58, sha256x2)`

**Comment by dcousens** [comment]
@fanatid maybe just `message-check` or something?

You would create a context `function (digest, bytes) { ... }`, which returns `encode`, and `decode`,  which would operate on `Buffer`.
Then `bs58check` would simply be the amalgamation of the two,  with `base58` doing the string encoding, and `message-check` doing `sha256x2` and `4` bytes?

**Comment by fanatid** [comment]
I don't know Daniel, I think that if we trying write package which will try embrace everything -- package will not be useful at all. I going to close this right now, maybe later we do this.

**Comment by dcousens** [comment]
@fanatid thoughts on a `varstruct` PR that takes a Codec,  and a checksum function?
