### ISSUE TITLE
Use as simple base58-bitcoin enconder, how to?

### ISSUE THREAD

**Issue by ppKrauss** [bitcoinjs/bs58check#11]
Example
```js
var bs58check = require('bs58check')
var decoded ='18e559fc6cb0e8de2ce8b50007d474a0d886208e698a07948671e0df520c1525';
console.log(bs58check.encode(decoded))
```
ERROR "TypeError: buf.copy is not a function".

PS: see also http://stackoverflow.com/q/43599252/287948

**Comment by dcousens** [comment]
@ppKrauss what are you using this with? node?

**Comment by ppKrauss** [comment]
Hi @dcousens , thanks. At my terminal `node --version` =  "v4.2.6"

**Comment by dcousens** [comment]
@ppKrauss a `Buffer` is expected... you're passing hex.

```
var decoded = new Buffer('18e...', 'hex')
...
```

**Comment by ppKrauss** [comment]
Thanks @dcousens, now is running (!). But something wrong:

```js
var decoded = new Buffer('18e559fc6cb0e8de2ce8b50007d474a0d886208e698a07948671e0df520c1525', 'hex')
console.log(bs58check.encode(decoded))
//    bs58check = Bxw5oZy9hvgxnwUtsC7w9vnFqSQvy1mm72mXFSCUAsepTrDjx
//    expected =  2gBdDRXoLPEhgf9Zd7zw5ujK1qcoPZoendBQJ22VjgqS
```
end result is not what is expected from a simple conversion (title of the issue), using "Bitcoin Address Base58 Encoder"  at http://lenschulwitz.com/base58 as reference.

**Comment by fanatid** [comment]
`2gBdDRXoLPEhgf9Zd7zw5ujK1qcoPZoendBQJ22VjgqS` is not valid bitcoin address
this is just `18e559fc6cb0e8de2ce8b50007d474a0d886208e698a07948671e0df520c1525` encoded in base58

**Comment by ppKrauss** [comment]
@fanatid  Yes, please read the title, "Use as simple base58-bitcoin enconder, how to?"... So, how can I do it with NodeJS and *bs58check*?

**Comment by fanatid** [comment]
> please read the title, "Use as simple base58-bitcoin enconder, how to?"

you title give zero information, if you want receive answer give a right question

**Comment by fanatid** [comment]
if you want receive `2gBdDRXoLPEhgf9Zd7zw5ujK1qcoPZoendBQJ22VjgqS` from `18e559fc6cb0e8de2ce8b50007d474a0d886208e698a07948671e0df520c1525` you need use package [bs58](https://github.com/cryptocoinjs/bs58):
```js
> require('bs58').encode(Buffer.from('18e559fc6cb0e8de2ce8b50007d474a0d886208e698a07948671e0df520c1525', 'hex'))
'2gBdDRXoLPEhgf9Zd7zw5ujK1qcoPZoendBQJ22VjgqS'
```
