### ISSUE TITLE
Conversion doesn't match wikipedia

### ISSUE THREAD

**Issue by CraigglesO** [bitcoinjs/bs58check#12]
https://en.bitcoin.it/wiki/Technical_background_of_version_1_Bitcoin_addresses

converting:
`00010966776006953D5567439E5E39F86A0D273BEED61967F6`
to:
`16UwLL9Risc3QfPqBUvKofHmBQ7wMtjvM`

does not work -_-

I have a feeling that the address is wrong on the website though. Just checking.
I get this:
`csU3KSAQMEYLPudM8UWJVxFfptcZSDvXF1LYM`

**Comment by dcousens** [comment]
How are you converting that?

**Comment by fanatid** [comment]
bs58check(00010966776006953D5567439E5E39F86A0D273BEE) = bs58(00010966776006953D5567439E5E39F86A0D273BEED61967F6) = 16UwLL9Risc3QfPqBUvKofHmBQ7wMtjvM

**Comment by CraigglesO** [comment]
Thank you! Sorry for not understanding!
