### ISSUE TITLE
bs58check-base?

### ISSUE THREAD

**Issue by fanatid** [bitcoinjs/bs58check#13]
[Decred](http://decred.org/) use [blake-256](https://en.wikipedia.org/wiki/BLAKE_(hash_function)) instead sha256.
Any ideas how other functions except sha256 can be used here?
New packages `bs58check-base`/`bs58check-blake256`/`bs58check-sha256`?

**Comment by dcousens** [comment]
I think it would nearly be better to just parameterize this implementation with a `sha256x2` default?
The extra module seems overkill.

**Comment by fanatid** [comment]
Make sense, second optional argument?

**Comment by dcousens** [comment]
See #14
