### ISSUE TITLE
Simple base58check program is 320k when built & minified for the browser

### ISSUE THREAD

**Issue by chr15m** [bitcoinjs/bs58check#21]
https://github.com/chr15m/bugout/issues/6#issuecomment-433890277

```javascript
var bs58check = require('base58check');
console.log(bs58check.decode('5Kd3NBUAdUnhyzenEwVLy9pBKxSwXvE9FMPyR4UKZvpe6E3AgLr'));
```

```shell
$ ./node_modules/.bin/browserify -s size size.js | ./node_modules/.bin/minify > size.min.js && du -h size.min.js
320K	size.min.js
```

**Comment by fanatid** [comment]
This is expected due to `create-hash` dep... you can analyze deps with https://github.com/hughsk/disc or with https://github.com/webpack-contrib/webpack-bundle-analyzer

**Comment by dcousens** [comment]
@fanatid do you have a breakdown you can post?

**Comment by fanatid** [comment]
Thanks to @headfire94 for webpack config example https://github.com/headfire94/base58check-webpack-example (`disc` for browserify do not give so much clear picture)
![screenshot from 2018-10-30 12-49-07](https://user-images.githubusercontent.com/2633065/47709918-7c876380-dc42-11e8-8907-7ec3a9759f2c.png)
