### ISSUE TITLE
suggestion to update the name of this repository to b58check or base58check

### ISSUE THREAD

**Issue by shea256** [bitcoinjs/bs58check#3]
I'm suggesting these because they are the labels that I've seen used most often. Either use the full description "base58check" or abbreviate "base" as "b" instead of "bs".

**Comment by dcousens** [comment]
It was to match https://github.com/cryptocoinjs/bs58

**Comment by dcousens** [comment]
In any case, if anyone searches for `base58check`,  this module comes up in searches.
