### ISSUE TITLE
3.0.1 breaks applications expecting a Buffer - Breaking Change

### ISSUE THREAD

**Issue by ADumaine** [bitcoinjs/bs58check#42]
3.0.1 returning a Unit8Array instead of a Buffer broke our node.js application.  

It's a bit frustrating there is no changelog indicating the new version no longer returns a buffer.  And the example still shows a Buffer being returned. I had to check the commits to track down the cause.

**Comment by junderw** [comment]
Re: breakage

v3.x.x is a major semver change, so breakage can only occur if you purposefully update major semver.

---

Re: Documentation

In regards to documentation and changelogs, pull requests are welcome.
