### ISSUE TITLE
extract sha256x2 to separate package

### ISSUE THREAD

**Issue by fanatid** [bitcoinjs/bs58check#6]
I don't know why this didn't happened earlier. It's very common operation (as `rmd160(sha256(x))`, probably also need own module?). We can put this package to <s>`crypto-browserify`</s>`cryptocoinjs` org.

/cc @dcousens @jprichardson

**Comment by dcousens** [comment]
Its also a 1 liner that is trivial to read... so IMHO seems pointless.

**Comment by fanatid** [comment]
but it's uses in many cases, instead wring function everywhere you can just require package

**Comment by dcousens** [comment]
But then you have the overhead of an extra package, which likely is going to be more burden then it is worth.

**Comment by fanatid** [comment]
Agree, it will be extra package, but one of the reasons: https://github.com/sindresorhus/ama/issues/10

**Comment by dcousens** [comment]
I agree with that,  except where the burden of maintenance is actually increased because now I [a random contributor, per say] have to check that `sha256x2` is using the same hashing algorithm that I am using such that it doesn't include more dependencies than necessary.
I don't think it really decreases complexity in this case.

**Comment by fanatid** [comment]
@dcousens can you advise, what name is better for `ripemd160(sha256(x))` -- `sha256ripemd160` or `ripemd160sha256`? or maybe you know better?

**Comment by jprichardson** [comment]
My naming preferences are either: 

(`sha256x2` AND `rmd160sha256`) OR (`hash256` AND `hash160`) 

@dcousens of the two, which do you like better :stuck_out_tongue_closed_eyes:?

**Comment by dcousens** [comment]
> hash256 AND hash160

Is the name we have used to date.
@fanatid if you're going to extract anything,  just pull out https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/crypto.js

**Comment by fanatid** [comment]
LOL
I created own repo https://github.com/fanatid/bitcoin-hash and found that [bitcoin-hash](https://www.npmjs.com/package/bitcoin-hash) already busy
now I found another repo https://github.com/cryptocoinjs/crypto-hashing

**Comment by jprichardson** [comment]
Haha, I forgot about crypto-hashing.

**Comment by jprichardson** [comment]
Maybe that's indicative of its utility?

**Comment by fanatid** [comment]
You mean that since you forgot about this package it's useless?

**Comment by jprichardson** [comment]
Yes, I'm wondering if that's the case. Maybe not "useless", but not as useful as I had originally thought.

**Comment by fanatid** [comment]
Or not so widely known.

Are you ok with removing `sha512` from `crypto-hasing` and bump version to `1.0.0`?

**Comment by fanatid** [comment]
Ref: #7
